Fix Pipeline

diff --git a/.github/workflows/ml-pipeline.yml b/.github/workflows/ml-pipeline.yml
--- a/.github/workflows/ml-pipeline.yml
+++ b/.github/workflows/ml-pipeline.yml
@@ -83,6 +83,11 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
+      - name: Debug params.yaml
+        run: |
+          pwd
+          ls -l
+          ls -l params.yaml || echo "params.yaml NOT FOUND"
       - name: Run data processing
         run: |
           PYTHONPATH=. python3 src/data_processing.py --input data/raw/mlops_dataset_v3.csv --output data/processed --params params.yaml
